import FUZZY_SEQUENCE from "./FuzzySequence"
import STARTS_WITH from "./StartsWith"
import STARTS_WITH_CASE_INSENSITIVE from "./StartsWithCaseInsensitive"
import ENDS_WITH from "./EndsWith"
import ENDS_WITH_CASE_INSENSITIVE from "./EndsWithCaseInsensitive"
import CONTAINS from "./Contains"
import CONTAINS_CASE_INSENSITIVE from "./ContainsCaseInsensitive"
import EQUALS from "./Equals"
import EQUALS_CASE_INSENSITIVE from "./EqualsCaseInsensitive"
import CONTAINS_ALL_WORDS from "./ContainsAllWords"
import BITAP from "./Bitap"
import BITAP_FULL from "./BitapFull"
import REGULAR_EXPRESSION from "./RegularExpression"
import REGULAR_EXPRESSION_CASE_INSENSITIVE from "./RegularExpressionCaseInsensitive"

export {
	FUZZY_SEQUENCE,
	STARTS_WITH,
	STARTS_WITH_CASE_INSENSITIVE,
	ENDS_WITH,
	ENDS_WITH_CASE_INSENSITIVE,
	CONTAINS,
	CONTAINS_CASE_INSENSITIVE,
	EQUALS,
	EQUALS_CASE_INSENSITIVE,
	CONTAINS_ALL_WORDS,
	BITAP,
	BITAP_FULL,
	REGULAR_EXPRESSION,
	REGULAR_EXPRESSION_CASE_INSENSITIVE
}

export default {
	FUZZY_SEQUENCE,
	STARTS_WITH,
	STARTS_WITH_CASE_INSENSITIVE,
	ENDS_WITH,
	ENDS_WITH_CASE_INSENSITIVE,
	CONTAINS,
	CONTAINS_CASE_INSENSITIVE,
	EQUALS,
	EQUALS_CASE_INSENSITIVE,
	CONTAINS_ALL_WORDS,
	BITAP,
	BITAP_FULL,
	REGULAR_EXPRESSION,
	REGULAR_EXPRESSION_CASE_INSENSITIVE
}
