import EXTRACT_ALL_NESTED from "./ExtractAllNested"
import RETURN_ROOT_ON_FIRST_MATCH from "./ReturnRootOnFirstMatch"
import RETURN_ROOT_ON_FIRST_MATCH_ORDERED from "./ReturnRootOnFirstMatchOrdered"

export {
    EXTRACT_ALL_NESTED,
    RETURN_ROOT_ON_FIRST_MATCH,
    RETURN_ROOT_ON_FIRST_MATCH_ORDERED
}

export default {
    EXTRACT_ALL_NESTED,
    RETURN_ROOT_ON_FIRST_MATCH,
    RETURN_ROOT_ON_FIRST_MATCH_ORDERED
}