name: tests-pr

on:
    pull_request:
        paths:
            - "src/**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: npm install && npm run build
